language: go
go:
  - "1.11.5"

install:
  - go get -u github.com/kardianos/govendor
  - export PATH=$PATH:$HOME/gopath/bin
  - govendor sync

script: ginkgo --randomizeAllSpecs --randomizeSuites --failOnPending --cover --trace --race --compilers=2 -covermode=atomic -coverpkg ./... ./...